sudo: false
language: go

go:
  - '1.10.1'

install:
  - go get golang.ysitd.cloud/tools/importer

script:
  - importer code.ysitd.cloud packages.yaml

deploy:
  provider: pages
  local-dir: dist
  fqdn: code.ysitd.cloud
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
